E-Commmerce/Controllers/ProductController.cs
using E_Commmerce.IReposatory;
using E_Commmerce.IReposatory.RepositoryModels;
using E_Commmerce.Models;
using E_Commmerce.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;
using System.Security.Cryptography.Xml;

namespace E_Commmerce.Controllers
{
    [Authorize(Roles = nameof(Roles.Admin))]
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IProductRepository productRepository, ICategoryRepository categoryRepository, IWebHostEnvironment webHostEnvironment)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
            _webHostEnvironment = webHostEnvironment;
        }


        [HttpGet]
        public IActionResult Index()
        {
            var listVm = _productRepository.GetAll.Select(
                p => new ProductViewModel()
                {
                    Id = p.Id,
                    Name = p.Name,
                    Price = p.Price,
                    Description = p.Description,
                    Category = p.Category,
                    CategoryId = p.CategoryId,
                    ImageViewModel = new UpdateImageViewModel() { ImageName = p.ImageName ?? "Defualt.png" },
                }
                ).ToList();
            ViewBag.Categories = CategoryDropDownList(_categoryRepository?.GetAll!);
            ViewBag.CategoryIds = _categoryRepository?.GetAll?.Select(c => c.Id).ToList();
            return View(listVm);
        }

        [HttpPost]
        public IActionResult Index(int CatId)
        {
            var listVm = _productRepository?.GetAll?.Select(
                p => new ProductViewModel()
                {
                    Id = p.Id,
                    Name = p.Name,
                    Price = p.Price,
                    Description = p.Description,
                    Category = p.Category,
                    CategoryId = p.CategoryId,
                    ImageViewModel = new UpdateImageViewModel() { ImageName = p.ImageName ?? "Defualt.png" }
                }
                ).Where(p => p.CategoryId == CatId).ToList();
            ViewBag.Categories = CategoryDropDownList(_categoryRepository?.GetAll!);
            return View(listVm);
        }


        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = CategoryDropDownList(_categoryRepository.GetAll!);
            return View();
        }

        [HttpPost]
        public IActionResult Create(ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var product = new Product
                {
                    Name = model.Name,
                    Price = model.Price,
                    Description = model.Description,
                    CategoryId = model.CategoryId,
                    Category = _categoryRepository.GetbyId((int)model.CategoryId!)
                };
                _productRepository.Add(product);
                return RedirectToAction("Index");
            }
            ViewBag.Categories = CategoryDropDownList(_categoryRepository.GetAll!);
            return View(model);
        }

        public IActionResult Details(int id)
        {
            var product = _productRepository.GetbyId(id);
            if (product == null)
            {
                return NotFound();
            }
            var ProdcutVm = new ProductViewModel()
            {
                Name = product.Name,
                Price = product.Price,
                Description = product.Description,
                CategoryId = product.CategoryId,
                Category = _categoryRepository.GetbyId((int)product.CategoryId!),
                ImageViewModel = new UpdateImageViewModel() { ImageName = product.ImageName ?? "Defualt.png" }
            };
            return View(ProdcutVm);
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var Product = _productRepository.GetbyId(Id);
            if (Product == null)
            {
                return NotFound();
            }
            var ProductVm = new ProductViewModel()
            {
                Id = Product.Id,
                Name = Product.Name,
                Price = Product.Price,
                Description = Product.Description,
                CategoryId = Product.CategoryId,
                Category = _categoryRepository.GetbyId((int)Product.CategoryId),
                ImageViewModel = new UpdateImageViewModel() { ImageName = Product.ImageName ?? "Defualt.png" }
            };
            ViewBag.Categories = CategoryDropDownList(_categoryRepository.GetAll!);
            return View(ProductVm);
        }

        [HttpPost]
        public IActionResult Edit(ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var product = new Product()
                {
                    Name = model.Name,
                    Price = model.Price,
                    Description = model.Description,
                    CategoryId = model.CategoryId,
                    Category = _categoryRepository.GetbyId((int)model.CategoryId!)
                };
                _productRepository.Update(model.Id, product);
                return RedirectToAction("Index");
            }
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ChangePhoto(ProductImage model)
        {
            if (ModelState.IsValid)
            {
                var product = _productRepository.GetbyId(model.Id);
                if (product != null)
                {
                    if (model.Image != null)
                    {
                        var path = Path.Combine(_webHostEnvironment.WebRootPath, "ProductImages", model.Image.FileName);
                        using var stream = new FileStream(path, FileMode.Create);
                        model.Image.CopyTo(stream);
                        product.ImageName = model.Image.FileName;
                        _productRepository.Update(model.Id, product);
                        return RedirectToAction(nameof(Index));
                    }
                }
                ModelState.AddModelError("", "No Image Selected !!");
            }
            return RedirectToAction(nameof(Edit), new { Id = model.Id });
        }



        public IActionResult Delete(int Id)
        {
            var product = _productRepository.GetbyId(Id);
            if (product == null)
            {
                return NotFound();
            }
            _productRepository.Remove(product);
            return RedirectToAction("Index");

        }



        private IEnumerable<SelectListItem> CategoryDropDownList(IEnumerable<Category> categories)
        {
            return categories.Select(c => new SelectListItem(text: c.Name, value: c.Id.ToString()));
        }


        [HttpGet]
        [AllowAnonymous]
        public IActionResult UserIndex()
        {
            var products = _productRepository?.GetAll?.Select(
                p => new ProductViewModel()
                {
                    Id = p.Id,
                    Name = p.Name,
                    Price = p.Price,
                    Description = p.Description,
                    CategoryId = p.CategoryId,
                    Category = _categoryRepository.GetbyId((int)p.CategoryId)
                }).ToList();
            return View(products);
        }


        [HttpGet]
        [AllowAnonymous]
        public IActionResult ListByCategory(int CategoryId)
        {
            var products = _categoryRepository.GetProducts(CategoryId)
                .Select(p => new ProductViewModel()
                {
                    Name = p.Name,
                    Description = p.Description,
                    CategoryId = p.CategoryId,
                    Price = p.Price,
                    Category = _categoryRepository.GetbyId((int)p.CategoryId!),
                    ImageViewModel = new UpdateImageViewModel() { ImageName = p.ImageName ?? "Defualt.png" }
                }).ToList();
            ViewBag.CatName = _categoryRepository?.GetbyId(CategoryId)?.Name;
            ViewBag.CatId = CategoryId;
            ViewBag.Products = products;
            return View(nameof(UserIndex), products);
        }



    }
}

E-Commmerce/Controllers/RoleController.cs
using E_Commmerce.Models;
using E_Commmerce.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.AccessControl;

namespace E_Commmerce.Controllers

{
    [Authorize(Roles = nameof(Roles.Admin))]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleRepository;
        public RoleController(RoleManager<IdentityRole> roleRepository)
        {
            _roleRepository = roleRepository;
        }

        public IActionResult Index()
        {
            var list = _roleRepository.Roles.Select(r => new RoleViewModel()
            {
                Id = r.Id,
                Name = r.Name
            }).ToList();
            return View(list);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole()
                {
                    Name = model.Name
                };
                var result = _roleRepository.CreateAsync(identityRole).Result;
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return View(model);
        }

        public IActionResult Delete(string Id)
        {
            var role = _roleRepository.FindByIdAsync(Id).Result;
            if (role != null)
            {
                var result = _roleRepository.DeleteAsync(role).Result;
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(string Id)
        {
            var role = _roleRepository.FindByIdAsync(Id).Result;
            var model = new RoleViewModel()
            {
                Id = role.Id,
                Name = role.Name
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = _roleRepository.FindByIdAsync(model.Id).Result;
                if (role != null)
                {
                    role.Name = model.Name;
                    var result = _roleRepository.UpdateAsync(role).Result;
                    if (result.Succeeded)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                            ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return View(model);
        }




    }
}

E-Commmerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - E_Commmerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/E_Commmerce.styles.css" asp-append-version="true" />
</head>
<body>
   <partial name="_NavBar" />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - E_Commmerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

E-Commmerce/Views/Shared/_NavBar.cshtml
@using Microsoft.AspNetCore.Identity;
@inject UserManager<ApplicationUser> usermanger
@{
    var user = usermanger?.GetUserAsync(User).Result;
    var profilePicture = user?.ImageName ?? "Defualt.png";
}

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-white bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Category" asp-action="UserIndex">
                <img src="/shopping-bag.png"  width="30px" />
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                   
                    @if(User.IsInRole(nameof(Roles.Admin)))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Manage Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Manage Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Manage Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Manage Users</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="UserIndex">Home</a>
                        </li>
                    }
                </ul>
                <ul class="navbar-nav flex-row-reverse">
                @if (!User.Identity.IsAuthenticated)
                {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                }
                else
                {
                 
                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                        <li>
                            <img src="/UserProfileImages/@user.ImageName" height="30px" class="rounded-circle me-1 mt-1" />
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Profile">Hello @User.Identity.Name  </a>
                        </li>
                }   
                </ul>

            </div>
        </div>
    </nav>
</header>

E-Commmerce/Views/Shared/_Pagination.cshtml
@{
    var prevDisabled = !Model.HasPrevoiusPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}


<a asp-action="Index"
   asp-route-PageNumber="1"
   class="btn btn-secondary @prevDisabled">
    First
</a>

<a asp-action="Index"
   asp-route-PageNumber="@(Model.PageIndex - 1)"
   class="btn btn-primary @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-PageNumber="@(Model.PageIndex + 1)"
   class="btn btn-primary @nextDisabled">
    Next
</a>
<a asp-action="Index"
   asp-route-PageNumber="@(Model.TotalPages )"
   class="btn btn-secondary @nextDisabled">
    Last
</a>

E-Commmerce/Views/Shared/_UserPagination.cshtml
@{
    var prevDisabled = !Model.HasPrevoiusPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}


<a asp-action="UserIndex"
   asp-route-PageNumber="1"
   class="btn btn-secondary @prevDisabled">
    First
</a>

<a asp-action="UserIndex"
   asp-route-PageNumber="@(Model.PageIndex - 1)"
   class="btn btn-primary @prevDisabled">
    Previous
</a>
<a asp-controller="Category"
    asp-action="UserIndex"
   asp-route-PageNumber="@(Model.PageIndex + 1)"
   class="btn btn-primary @nextDisabled">
    Next
</a>
<a asp-action="UserIndex"
   asp-route-PageNumber="@(Model.TotalPages )"
   class="btn btn-secondary @nextDisabled">
    Last
</a>