E-Commmerce/Models/Category.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace E_Commmerce.Models
{
    [Table("Categories")]
    public class Category
    {
        public int Id { get; set; }

        [Required]
        [Column("CategroyName", TypeName = "nvarchar(100)")]
        public string Name { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public ICollection<Product> Products { get; set; } = new List<Product>();
        public string? ImageName { get; set; }
        public string? ImageContentType { get; set; }


    }
}

E-Commmerce/ViewModels/CategoryViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace E_Commmerce.ViewModels
{
    public class CategoryViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Category Name"), MaxLength(100), MinLength(3)]
        public string Name { get; set; } = string.Empty;
        [StringLength(500), MinLength(3)]
        public string Description { get; set; } = string.Empty;
        public List<ProductViewModel>? Products { get; set; }

        public int ProductsCount;

        public UpdateImageViewModel? ImageViewModel { get; set; }


    }
}

E-Commmerce/Controllers/CategoryController.cs
using E_Commmerce.Helper;
using E_Commmerce.IReposatory;
using E_Commmerce.Migrations;
using E_Commmerce.Models;
using E_Commmerce.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using NuGet.Packaging.Core;
using System.ComponentModel.DataAnnotations;

namespace E_Commmerce.Controllers
{

    [Authorize(Roles = nameof(Roles.Admin))]
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public CategoryController(ICategoryRepository categoryRepository, IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
            _categoryRepository = categoryRepository;
        }

        public IActionResult Index(int PageNumber = 1)
        {
            var list = _categoryRepository.GetAll.Select(c => new CategoryViewModel()
            {
                Id = c.Id,
                Name = c.Name,
                Description = c.Description,
                ImageViewModel = new UpdateImageViewModel() { ImageName = c.ImageName ?? "Defualt.png" },
                ProductsCount = c.Products.Count
            }).ToList();

            PageList<CategoryViewModel> Categories = PageList<CategoryViewModel>.Create(list, PageNumber, 5);
            return View(Categories);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CategoryViewModel model)
        {

            if (ModelState.IsValid)
            {
                var category = new Category()
                {
                    Name = model.Name,
                    Description = model.Description
                };
                _categoryRepository.Add(category);

                var count = _categoryRepository.GetAll.Count();
                var PageNumber = (int)Math.Ceiling(count / 5d);
                ViewBag.TotalPages = PageNumber;
                return RedirectToAction(nameof(Index), new { PageNumber = PageNumber });
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int Id, int PageNumber)
        {
            var Category = _categoryRepository.GetbyId(Id);
            if (Category != null)
            {
                var model = new CategoryViewModel()
                {
                    Id = Category.Id,
                    Name = Category.Name,
                    Description = Category.Description,
                    ImageViewModel = new UpdateImageViewModel() { ImageName = Category.ImageName ?? "Defualt.png" }
                };
                ViewBag.pageIndex = PageNumber;
                return View(model);
            }
            return NotFound();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CategoryViewModel model, int PageNumber)
        {
            if (ModelState.IsValid)
            {
                var category = new Category()
                {
                    Id = model.Id,
                    Name = model.Name,
                    Description = model.Description
                };
                _categoryRepository.Update(model.Id, category);
                return RedirectToAction(nameof(Index), new { PageNumber = PageNumber });
            }
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult ChangePhoto(CategoryImage model, int PageNumber)
        {
            if (ModelState.IsValid)
            {
                var Category = _categoryRepository.GetbyId(model.Id);
                if (Category != null)
                {
                    if (model.Image != null)
                    {
                        var path = Path.Combine(_webHostEnvironment.WebRootPath, "CategoryImages", model.Image.FileName);
                        using var stream = new FileStream(path, FileMode.Create);
                        model.Image.CopyTo(stream);
                        Category.ImageName = model.Image.FileName;
                        _categoryRepository.Update(model.Id, Category);
                        return RedirectToAction(nameof(Index), new { PageNumber = PageNumber });
                    }
                }
                ModelState.AddModelError("", "No Image Selected !!");
            }
            return RedirectToAction(nameof(Edit), new { Id = model.Id });
        }


        public IActionResult Delete(int Id, int PageNumber)
        {
            var Category = _categoryRepository.GetbyId(Id);
            if (Category != null)
            {
                _categoryRepository.Remove(Category);
                return RedirectToAction(nameof(Index), new { PageNumber = PageNumber });
            }
            return NotFound();
        }

        [HttpGet]
        public IActionResult Details(int Id)
        {
            var Category = _categoryRepository.GetbyId(Id);
            if (Category != null)
            {
                var CategoryViewModel = new CategoryViewModel()
                {
                    Id = Category.Id,
                    Name = Category.Name,
                    Description = Category.Description,
                    ImageViewModel = new UpdateImageViewModel { ImageName = Category.ImageName ?? "Defualt.png" },
                    ProductsCount = Category.Products.Count
                };

                return View(CategoryViewModel);
            }
            return NotFound();
        }

        /* public IActionResult        {
             var result = _categoryRepository.Search(term);
             return View("Index",result);
         }*/

        [HttpGet]
        public IActionResult ShowAll(int CategoryId)
        {
            var products = _categoryRepository.GetProducts(CategoryId);
            ViewBag.CatName = _categoryRepository?.GetbyId(CategoryId)?.Name;
            ViewBag.CatId = CategoryId;
            return View(products);
        }


        [HttpPost]
        public IActionResult ShowAll(int catid, string term)
        {
            var list = _categoryRepository.Search(catid, term);
            ViewBag.CatName = _categoryRepository?.GetbyId(catid)?.Name;
            return View(list);
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult UserIndex(int PageNumber = 1)
        {
            var categories = _categoryRepository.GetAll.Select(c => new CategoryViewModel()
            {
                Id = c.Id,
                Name = c.Name,
                Description = c.Description,
                ImageViewModel = new UpdateImageViewModel() { ImageName = c.ImageName ?? "Defualt.png" }
            }).ToList();

            PageList<CategoryViewModel> categoryViews = PageList<CategoryViewModel>.Create(categories, PageNumber, 3);

            return View(categoryViews);
        }




    }
}

E-Commmerce/Controllers/ProductController.cs
using E_Commmerce.IReposatory;
using E_Commmerce.IReposatory.RepositoryModels;
using E_Commmerce.Models;
using E_Commmerce.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;
using System.Security.Cryptography.Xml;

namespace E_Commmerce.Controllers
{
    [Authorize(Roles = nameof(Roles.Admin))]
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IProductRepository productRepository, ICategoryRepository categoryRepository, IWebHostEnvironment webHostEnvironment)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
            _webHostEnvironment = webHostEnvironment;
        }


        [HttpGet]
        public IActionResult Index()
        {
            var listVm = _productRepository.GetAll.Select(
                p => new ProductViewModel()
                {
                    Id = p.Id,
                    Name = p.Name,
                    Price = p.Price,
                    Description = p.Description,
                    Category = p.Category,
                    CategoryId = p.CategoryId,
                    ImageViewModel = new UpdateImageViewModel() { ImageName = p.ImageName ?? "Defualt.png" },
                }
                ).ToList();
            ViewBag.Categories = CategoryDropDownList(_categoryRepository?.GetAll!);
            ViewBag.CategoryIds = _categoryRepository?.GetAll?.Select(c => c.Id).ToList();
            return View(listVm);
        }

        [HttpPost]
        public IActionResult Index(int CatId)
        {
            var listVm = _productRepository?.GetAll?.Select(
                p => new ProductViewModel()
                {
                    Id = p.Id,
                    Name = p.Name,
                    Price = p.Price,
                    Description = p.Description,
                    Category = p.Category,
                    CategoryId = p.CategoryId,
                    ImageViewModel = new UpdateImageViewModel() { ImageName = p.ImageName ?? "Defualt.png" }
                }
                ).Where(p => p.CategoryId == CatId).ToList();
            ViewBag.Categories = CategoryDropDownList(_categoryRepository?.GetAll!);
            return View(listVm);
        }


        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = CategoryDropDownList(_categoryRepository.GetAll!);
            return View();
        }

        [HttpPost]
        public IActionResult Create(ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var product = new Product
                {
                    Name = model.Name,
                    Price = model.Price,
                    Description = model.Description,
                    CategoryId = model.CategoryId,
                    Category = _categoryRepository.GetbyId((int)model.CategoryId!)
                };
                _productRepository.Add(product);
                return RedirectToAction("Index");
            }
            ViewBag.Categories = CategoryDropDownList(_categoryRepository.GetAll!);
            return View(model);
        }

        public IActionResult Details(int id)
        {
            var product = _productRepository.GetbyId(id);
            if (product == null)
            {
                return NotFound();
            }
            var ProdcutVm = new ProductViewModel()
            {
                Name = product.Name,
                Price = product.Price,
                Description = product.Description,
                CategoryId = product.CategoryId,
                Category = _categoryRepository.GetbyId((int)product.CategoryId!),
                ImageViewModel = new UpdateImageViewModel() { ImageName = product.ImageName ?? "Defualt.png" }
            };
            return View(ProdcutVm);
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var Product = _productRepository.GetbyId(Id);
            if (Product == null)
            {
                return NotFound();
            }
            var ProductVm = new ProductViewModel()
            {
                Id = Product.Id,
                Name = Product.Name,
                Price = Product.Price,
                Description = Product.Description,
                CategoryId = Product.CategoryId,
                Category = _categoryRepository.GetbyId((int)Product.CategoryId),
                ImageViewModel = new UpdateImageViewModel() { ImageName = Product.ImageName ?? "Defualt.png" }
            };
            ViewBag.Categories = CategoryDropDownList(_categoryRepository.GetAll!);
            return View(ProductVm);
        }

        [HttpPost]
        public IActionResult Edit(ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var product = new Product()
                {
                    Name = model.Name,
                    Price = model.Price,
                    Description = model.Description,
                    CategoryId = model.CategoryId,
                    Category = _categoryRepository.GetbyId((int)model.CategoryId!)
                };
                _productRepository.Update(model.Id, product);
                return RedirectToAction("Index");
            }
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ChangePhoto(ProductImage model)
        {
            if (ModelState.IsValid)
            {
                var product = _productRepository.GetbyId(model.Id);
                if (product != null)
                {
                    if (model.Image != null)
                    {
                        var path = Path.Combine(_webHostEnvironment.WebRootPath, "ProductImages", model.Image.FileName);
                        using var stream = new FileStream(path, FileMode.Create);
                        model.Image.CopyTo(stream);
                        product.ImageName = model.Image.FileName;
                        _productRepository.Update(model.Id, product);
                        return RedirectToAction(nameof(Index));
                    }
                }
                ModelState.AddModelError("", "No Image Selected !!");
            }
            return RedirectToAction(nameof(Edit), new { Id = model.Id });
        }



        public IActionResult Delete(int Id)
        {
            var product = _productRepository.GetbyId(Id);
            if (product == null)
            {
                return NotFound();
            }
            _productRepository.Remove(product);
            return RedirectToAction("Index");

        }



        private IEnumerable<SelectListItem> CategoryDropDownList(IEnumerable<Category> categories)
        {
            return categories.Select(c => new SelectListItem(text: c.Name, value: c.Id.ToString()));
        }


        [HttpGet]
        [AllowAnonymous]
        public IActionResult UserIndex()
        {
            var products = _productRepository?.GetAll?.Select(
                p => new ProductViewModel()
                {
                    Id = p.Id,
                    Name = p.Name,
                    Price = p.Price,
                    Description = p.Description,
                    CategoryId = p.CategoryId,
                    Category = _categoryRepository.GetbyId((int)p.CategoryId)
                }).ToList();
            return View(products);
        }


        [HttpGet]
        [AllowAnonymous]
        public IActionResult ListByCategory(int CategoryId)
        {
            var products = _categoryRepository.GetProducts(CategoryId)
                .Select(p => new ProductViewModel()
                {
                    Name = p.Name,
                    Description = p.Description,
                    CategoryId = p.CategoryId,
                    Price = p.Price,
                    Category = _categoryRepository.GetbyId((int)p.CategoryId!),
                    ImageViewModel = new UpdateImageViewModel() { ImageName = p.ImageName ?? "Defualt.png" }
                }).ToList();
            ViewBag.CatName = _categoryRepository?.GetbyId(CategoryId)?.Name;
            ViewBag.CatId = CategoryId;
            ViewBag.Products = products;
            return View(nameof(UserIndex), products);
        }



    }
}

E-Commmerce/Views/Category/Create.cshtml
@model CategoryViewModel

@{
    ViewBag.Title = "Create Category";
}
<form method="post" asp-action="Create" >
    <div class="card ">
        <div class="card-header">
            <h3 class="card-title">Create Category</h3
        </div>
        <div class="card-body">

            <div class="form-group">
                    <label asp-for="Name" class="control-label mb-2"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
             </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label mb-2"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="mt-2" >
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </div>
    </div>
</form>

<div class="mt-0">
    <a asp-action="Index" asp-route-PageNumber="@ViewBag.TotalPages" class="page-link text-center text-black font-monospace  ">Back to List</a>
</div>

 @section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

E-Commmerce/Views/Category/Details.cshtml
@model CategoryViewModel
@{
    ViewBag.Title = "Details";
}

<div class="card-group">
    <div class="card-img">
        <img src="/CategoryImages/@Model.ImageViewModel.ImageName" width="200px" />
    </div>
    <div class="card-header">
        <h3>@Model.Name</h3>
    </div>
    <div class="card-body">
        <p class="card-text">Description: @Model.Description</p>
        <p class="card-text">In Stock: @Model?.ProductsCount</p>
    </div>
    <div>
        <a asp-action="Index" class="btn btn-secondary m-3">Back to List</a>
    </div>

</div>

E-Commmerce/Views/Category/Edit.cshtml
@model CategoryViewModel

@{
    ViewBag.Title = "Edit Category";
}

<img src="/CategoryImages/@Model.ImageViewModel.ImageName " width="200px" class="rounded" />
<partial name="_ChangeCategoryForm" model="new CategoryImage() {Id = Model.Id} ">



<form method="post" asp-action="Edit" asp-route-PageNumber="@ViewBag.pageIndex" >
    <div class="card mt-3">
        <div class="card-header">
            <h3 class="card-title">Edit Category</h3
        </div>
        <div class="card-body">
            <input hidden asp-for="Id" value="@Model.Id" />
            <div class="form-group">
                    <label asp-for="Name" class="control-label mb-2"  ></label>
                    <input asp-for="Name" value="@Model.Name" class="form-control"  />
                    <span asp-validation-for="Name" class="text-danger"></span>
             </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label mb-2"></label>
                <input asp-for="Description" value="@Model.Description" class="form-control">
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="mt-2" >
                <button type="submit" class="btn btn-primary">Edit</button>
            </div>
        </div>
    </div>
</form>

<div class="mt-0">
    <a asp-action="Index" class="page-link text-center text-black font-monospace  ">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

E-Commmerce/Views/Category/Index.cshtml
@model PageList<CategoryViewModel>

@{
    ViewBag.Title = "All Cateigories";
}



<h2>All Categories</h2>
<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>



<table class="table table-bordered text-md-center align-middle">
    <thead>
        <th>#</th>
        <th>Category Name </th>
        <th>Description</th>
        <th>Category Image</th>
        <th>Actions</th>
    </thead>
    <tbody>
        @for(int i = 0;i<Model.Count();i++)
        {
            
            <tr>
                <td>@(i+1)</td>
                <td>
                    <h4 class="header">@Model[i].Name </h4>
                   @if(Model[i].ProductsCount == 0)
                    {
                        <span class="paragraph">Empty</span>
                    }
                    else
                    {
                        <span class="paragraph">@Model[i].ProductsCount</span>
                    }
                </td>
                <td>@Model[i].Description</td>
                <td><img src="/CategoryImages/@Model[i]?.ImageViewModel?.ImageName" width="150px" class="rounded" /></td>
                <td>
                    <a class="btn btn-danger"
                       asp-action="Delete" asp-route-Id=@Model[i].Id asp-route-PageNumber="@Model.PageIndex"
                       onclick="return confirm('Are You Sure To Delete')">Delete</a>
                       |
                    <a asp-action="Edit" asp-route-Id="@Model[i].Id" asp-route-PageNumber="@Model.PageIndex" class="btn btn-secondary">Edit</a>
                       |
                    <a asp-action="Details" asp-route-Id="@Model[i].Id"  class="btn btn-info text-white">Details</a>
                       |
                    <a asp-action="ShowAll" asp-route-CategoryId="@Model[i].Id" class="btn btn-dark text-white">Show All</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<partial name="_Pagination" />

<style>
    .paragraph{
        background-color: #363432;
        color: white;
        padding: 4px 8px;
        text-align: center;
        border-radius: 5px;
    }
    .header{
        display:inline-block;
    }
</style>

E-Commmerce/Views/Category/ShowAll.cshtml
@model List<Product>

@{
    ViewBag.Title = "ShowAll";
}
@if(Model.Count!=0)
{
    <h2 class="mb-3">@ViewBag.CatName || (@Model.Count) In the Stock</h2>
}
else
{
    <h2 class="mb-3">No Product In The Stock</h2>
}

<form method="post" asp-action="ShowAll">
    <div class="input-group mb-3">
        <input type="text" class="form-control" id="myInput" placeholder="Search" name="term" aria-label="Recipient's username" aria-describedby="button-addon2">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="submit" asp-route-catId="@ViewBag.CatId">Search</button>
        </div>
    </div>
</form>


@foreach(var product in Model)
{
    <div class="card">
        <div class="card-header">
            <h3>@product.Name</h3>
        </div>
        <div class="card-body">
            <p>@product.Description</p>
            <p>@product.Price</p>
            <p>@product?.Category?.Name</p>
        </div>
<div class="card-footer">
            <a asp-controller="Product" asp-action="Details" asp-route-id="@product.Id" class="btn btn-info text-white">Details</a>
            <a asp-controller="Product" asp-action="Edit" asp-route-id="@product.Id" class="btn btn-secondary">Edit</a>
            <a asp-controller="Product" asp-action="Delete" asp-route-id="@product.Id" class="btn btn-danger" onclick="return confirm('Are You Sure To Delete')">Delete</a>
    </div>
</div>
    <hr />
}


<div>
    <a asp-action="Index" class="btn btn-secondary mt-2">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

E-Commmerce/Views/Category/UserIndex.cshtml
@model PageList<CategoryViewModel>

@{
    ViewBag.Title = "Categories";
}

@foreach(var item in Model)
{
    <div class="card card-subtitle">
        <div class="card-img">
            <img src="/CategoryImages/@item.ImageViewModel.ImageName" width="20%" class="rounded-3">
        </div>
        <div class="card-header">
            <h3>   @item.Name</h3>
        </div>
        <div class="card-body">
            <p>  @item.Description</p>
        </div>
        <div class="card-footer">
            <a class="btn btn-primary" asp-controller="Product" asp-action="ListByCategory" asp-route-CategoryId="@item.Id">Show All</a>
        </div>
    </div>
    <hr />
}


<style>
    hr{
        border: 6px solid #002333;
        border-radius: 010px;
    }
</style>

<partial name="_UserPagination" />

E-Commmerce/Views/Category/_ChangeCategoryForm.cshtml
@model CategoryImage
<form method="post" asp-controller="Category" asp-action="ChangePhoto" asp-route-PageNumber="@ViewBag.pageIndex" enctype="multipart/form-data">
    <div class="input-group-sm">
        <input hidden asp-for="Id" value="@Model.Id" />
        <input asp-for="Image" type="file" class="form-control" />
        <button type="submit"  class="btn btn-primary mt-2">Change Image</button>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}